version: '3.6'

services:
  # Backend API
  udupay-api:
    container_name: backend
    build: ./
    command: yarn run dev

    working_dir: /usr/src/udupay-api

    environment:
      POSTGRES_URI: postgres://postgres:topple@postgres:5432/udupay

    # links server with db
    links:
      - postgres
    ports:
      - '3050:3050'
    # enables our container filesystem to see local dev changes & updates itself
    volumes:
      - ./:/usr/src/udupay-api

  # Database - Postgres
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: topple
      POSTGRES_DB: udupay
      POSTGRES_HOST: postgres
    image: Postgres
    # postgres default port
    ports:
      - '5432:5432'
