version: "3.3"

services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_USER: ecoden
      POSTGRES_PASSWORD: topple
      POSTGRES_DB: udupay
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: db@udupay.com
      PGADMIN_DEFAULT_PASSWORD: topple
    restart: always
    ports:
      - 8080:80
